### ISSUE TITLE
Switch to DoubleFloats.jl

### ISSUE THREAD

**Issue by simonbyrne** [ivanslapnicar/Arrowhead.jl#10]
I am deprecating DoubleDouble.jl for 0.7 in favour of [DoubleFloats.jl](https://github.com/JuliaMath/DoubleFloats.jl).

**Comment by ivanslapnicar** [comment]
There is new version of package for Julia 1.0+.
It  incorporates just the main file `DoubleDouble.jl`, adapted for Julia 1.0+, since it is fster than 
`DoubleFloats.jl`.
